Skip to content
rohanp1493
SauceDemo-Framework
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
.github/workflows/selenium-tests.yml
fix the yaml file #14
All jobs
Run details
Workflow file for this run
.github/workflows/selenium-tests.yml at 3124640
# Name of this workflow
name: Selenium Tests

# WHEN does this run?
# Every time you push code to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Also allows manual trigger from GitHub UI
  workflow_dispatch:

# WHAT does it do?
jobs:
  run-tests:

    # Use Ubuntu Linux machine
    # GitHub provides this for free
    runs-on: ubuntu-latest

    steps:

      # Step 1 — Download your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3 — Cache Maven dependencies
      # So it doesn't download jars every time
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      # Step 4 — Install Chrome browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      # Step 5 — Run your tests!
      # headless=true because server has no screen
      - name: Run Selenium Tests
 Check failure on line 50 in .github/workflows/selenium-tests.yml


GitHub Actions
/ .github/workflows/selenium-tests.yml
Invalid workflow file

You have an error in your yaml syntax on line 50
       	run: mvn clean test -Dheadless=true
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

      # Step 6 — Upload Allure results
      # Even if tests fail — still upload results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 30

      # Step 7 — Upload Surefire reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports
          retention-days: 30
